version: "3"
networks:
  myproject:
    external: true
services:
  # events-project:
  #  image: orensimple/project:0.0.1
  #  depends_on:
  #    - myproject-db
  #    - myproject-flyway
  #  ports:
  #    - "8088:8088"
  #    - "9110:9110"
  #  networks:
  #    - myproject

  # Run the DB
  myproject-db3:
    image: postgres:10.11
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
    networks:
      - myproject

  # Apply migrations to the DB
  myproject-flyway3:
    image: boxfuse/flyway:5.1.4
    volumes:
      - ./db/migration:/flyway/sql
    command: -url=jdbc:postgresql://myproject-db3/br -user=db-user -password=db-password migrate
    depends_on:
      - myproject-db3
    networks:
      - myproject

  myproject-rabbitmq:
    image: "rabbitmq:3-management"
    networks:
      - myproject
    ports:
      - "15672:15672"
      - "5672:5672"