log_file: "./main.log"

log_level:
  command: "Debug"
  file: "Info"

http_listen:
  ip: "127.0.0.1"
  port: 7002

postgres:
  ip: "127.0.0.1"
  port: 5432
  db: "br"
  user: "db-user"
  passwd: "db-password"

amqp:
  ip: "127.0.0.1"
  port: 5672
  user: "guest"
  passwd: "guest"

report_type:
  show: 1
  conversion: 2